# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

connection: &connection
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  min_messages: warning

development:
  <<: *connection
  database: edgar_development

test: &test
  <<: *connection
  database: edgar_test

cucumber:
  <<: *test
