# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Territory.create(id: 2, region_id: 1, name: 'Cambodia', division_id: 1)
Territory.create(id: 5, region_id: 1, name: 'Fiji', division_id: 1)
Territory.create(id: 6, region_id: 1, name: 'Solomon Islands', division_id: 1)
Territory.create(id: 8, region_id: 1, name: 'Kiribati', division_id: 1)
Territory.create(id: 9, region_id: 1, name: 'Tonga', division_id: 1)
Territory.create(id: 10, region_id: 1, name: 'Micronesia', division_id: 1)
Territory.create(id: 11, region_id: 1, name: 'Marshall Islands', division_id: 1)
Territory.create(id: 12, region_id: 1, name: 'American Samoa', division_id: 1)
Territory.create(id: 13, region_id: 1, name: 'Palau', division_id: 1)
Territory.create(id: 14, region_id: 1, name: 'Narau', division_id: 1)
Territory.create(id: 3, region_id: 1, name: 'Papa New Guinea', division_id: 1)
Territory.create(id: 7, region_id: 1, name: 'Guam', division_id: 1)
Territory.create(id: 4, region_id: 1, name: 'New Zealand', division_id: 1)
Territory.create(id: 15, region_id: 1, name: 'Vietnam', division_id: 1)
Territory.create(id: 1, region_id: 1, name: 'Australia', division_id: 1)
Territory.create(id: 80, region_id: 10, name: 'Arunachal Pradesh(India)', division_id: 2)
Territory.create(id: 81, region_id: 10, name: 'Puducherry(India)', division_id: 2)
Territory.create(id: 82, region_id: 10, name: 'Mizoram(India)', division_id: 2)
Territory.create(id: 83, region_id: 10, name: 'Bhutan', division_id: 2)
Territory.create(id: 84, region_id: 10, name: 'Sikkim(India)', division_id: 2)
Territory.create(id: 85, region_id: 10, name: 'Andoman & Nicobar(India)', division_id: 2)
Territory.create(id: 79, region_id: 10, name: 'Nagaland(India)', division_id: 2)
Territory.create(id: 77, region_id: 10, name: 'Manipur(India)', division_id: 2)
Territory.create(id: 78, region_id: 10, name: 'Meghalaya(India)', division_id: 2)
Territory.create(id: 76, region_id: 10, name: 'Tripura(India)', division_id: 2)
Territory.create(id: 75, region_id: 10, name: 'Assam(India)', division_id: 2)
Territory.create(id: 74, region_id: 10, name: 'Jharkhand(India)', division_id: 2)
Territory.create(id: 73, region_id: 10, name: 'W. Bengal(India)', division_id: 2)
Territory.create(id: 72, region_id: 10, name: 'Bangladesh', division_id: 2)
Territory.create(id: 91, region_id: 11, name: 'Uttarakhand(India)', division_id: 2)
Territory.create(id: 90, region_id: 11, name: 'Chattisgarh(India)', division_id: 2)
Territory.create(id: 89, region_id: 11, name: 'Nepal(India)', division_id: 2)
Territory.create(id: 88, region_id: 11, name: 'Madhya Pradesh(India)', division_id: 2)
Territory.create(id: 87, region_id: 11, name: 'Bihar(India)', division_id: 2)
Territory.create(id: 86, region_id: 11, name: 'Uttar Pradesh(India)', division_id: 2)
Territory.create(id: 99, region_id: 12, name: 'Goa(India)', division_id: 2)
Territory.create(id: 98, region_id: 12, name: 'Kerala(India)', division_id: 2)
Territory.create(id: 97, region_id: 12, name: 'Odisha(India)', division_id: 2)
Territory.create(id: 96, region_id: 12, name: 'Karnataka(India)', division_id: 2)
Territory.create(id: 95, region_id: 12, name: 'Rajasthan(India)', division_id: 2)
Territory.create(id: 94, region_id: 12, name: 'Tamil Nadu(India)', division_id: 2)
Territory.create(id: 93, region_id: 12, name: 'Andhra Pradesh(India)', division_id: 2)
Territory.create(id: 92, region_id: 12, name: 'Maharashtra(India)', division_id: 2)
Territory.create(id: 106, region_id: 13, name: 'Chandigarh(India)', division_id: 2)
Territory.create(id: 107, region_id: 13, name: 'Maldives', division_id: 2)
Territory.create(id: 108, region_id: 13, name: 'Damadu & Diu(India)', division_id: 2)
Territory.create(id: 109, region_id: 13, name: 'Lakshadaweep(India)', division_id: 2)
Territory.create(id: 105, region_id: 13, name: 'Himachal Pradesh(India)', division_id: 2)
Territory.create(id: 104, region_id: 13, name: 'Jammu & Kashmir(India)', division_id: 2)
Territory.create(id: 100, region_id: 13, name: 'Delhi(India)', division_id: 2)
Territory.create(id: 103, region_id: 13, name: 'Haryana(India)', division_id: 2)
Territory.create(id: 102, region_id: 13, name: 'Punjab(India)', division_id: 2)
Territory.create(id: 101, region_id: 13, name: 'Gujurat(India)', division_id: 2)
Territory.create(id: 110, region_id: 13, name: 'Pakistan', division_id: 2)
Territory.create(id: 115, region_id: 14, name: 'Palestine', division_id: 2)
Territory.create(id: 113, region_id: 14, name: 'Jordan', division_id: 2)
Territory.create(id: 114, region_id: 14, name: 'Lebanon', division_id: 2)
Territory.create(id: 112, region_id: 14, name: 'Syria', division_id: 2)
Territory.create(id: 111, region_id: 14, name: 'Saudi Arabia', division_id: 2)
Territory.create(id: 118, region_id: 14, name: 'Afghanistan', division_id: 2)
Territory.create(id: 116, region_id: 14, name: 'Iraq', division_id: 2)
Territory.create(id: 117, region_id: 14, name: 'Iran', division_id: 2)
Territory.create(id: 124, region_id: 15, name: 'Armenia', division_id: 2)
Territory.create(id: 123, region_id: 15, name: 'Georgia', division_id: 2)
Territory.create(id: 125, region_id: 15, name: 'Cyprus', division_id: 2)
Territory.create(id: 122, region_id: 15, name: 'Bulgaria', division_id: 2)
Territory.create(id: 121, region_id: 15, name: 'Azerbaijan', division_id: 2)
Territory.create(id: 120, region_id: 15, name: 'Greece', division_id: 2)
Territory.create(id: 119, region_id: 15, name: 'Turkey', division_id: 2)
Territory.create(id: 135, region_id: 16, name: 'Djbouti', division_id: 2)
Territory.create(id: 136, region_id: 16, name: 'Comoros', division_id: 2)
Territory.create(id: 134, region_id: 16, name: 'Mauritania', division_id: 2)
Territory.create(id: 133, region_id: 16, name: 'Libya', division_id: 2)
Territory.create(id: 132, region_id: 16, name: 'Somalia', division_id: 2)
Territory.create(id: 130, region_id: 16, name: 'Chad', division_id: 2)
Territory.create(id: 131, region_id: 16, name: 'Tunisia', division_id: 2)
Territory.create(id: 129, region_id: 16, name: 'Morocco', division_id: 2)
Territory.create(id: 128, region_id: 16, name: 'Algeria', division_id: 2)
Territory.create(id: 127, region_id: 16, name: 'Sudan', division_id: 2)
Territory.create(id: 126, region_id: 16, name: 'Egypt', division_id: 2)
Territory.create(id: 145, region_id: 17, name: 'Botswana', division_id: 3)
Territory.create(id: 146, region_id: 17, name: 'Gambia', division_id: 3)
Territory.create(id: 143, region_id: 17, name: 'Namibia', division_id: 3)
Territory.create(id: 144, region_id: 17, name: 'Lesotho', division_id: 3)
Territory.create(id: 148, region_id: 17, name: 'Swaziland', division_id: 3)
Territory.create(id: 142, region_id: 17, name: 'Liberia', division_id: 3)
Territory.create(id: 147, region_id: 17, name: 'Maritius', division_id: 3)
Territory.create(id: 141, region_id: 17, name: 'Sierra Leone', division_id: 3)
Territory.create(id: 139, region_id: 17, name: 'Zambia', division_id: 3)
Territory.create(id: 140, region_id: 17, name: 'Zimbabwe', division_id: 3)
Territory.create(id: 138, region_id: 17, name: 'Ghana', division_id: 3)
Territory.create(id: 137, region_id: 17, name: 'S. Africa', division_id: 3)
Territory.create(id: 157, region_id: 18, name: 'Montenegro', division_id: 3)
Territory.create(id: 154, region_id: 18, name: 'Kosovo', division_id: 3)
Territory.create(id: 155, region_id: 18, name: 'Macedonia', division_id: 3)
Territory.create(id: 153, region_id: 18, name: 'Albania', division_id: 3)
Territory.create(id: 152, region_id: 18, name: 'Bosnia', division_id: 3)
Territory.create(id: 149, region_id: 18, name: 'Serbia', division_id: 3)
Territory.create(id: 151, region_id: 18, name: 'Croatia', division_id: 3)
Territory.create(id: 156, region_id: 18, name: 'Slovenia', division_id: 3)
Territory.create(id: 150, region_id: 18, name: 'Nigeria', division_id: 3)
Territory.create(id: 167, region_id: 19, name: 'Bahamas', division_id: 3)
Territory.create(id: 168, region_id: 19, name: 'US Virgin Islands', division_id: 3)
Territory.create(id: 162, region_id: 19, name: 'Uganda', division_id: 3)
Territory.create(id: 161, region_id: 19, name: 'Kenya', division_id: 3)
Territory.create(id: 160, region_id: 19, name: 'Tanzania', division_id: 3)
Territory.create(id: 166, region_id: 19, name: 'S. Carolina(USA)', division_id: 3)
Territory.create(id: 158, region_id: 19, name: 'Israel', division_id: 3)
Territory.create(id: 159, region_id: 19, name: 'Ethiopia', division_id: 3)
Territory.create(id: 165, region_id: 19, name: 'N. Carolina(USA)', division_id: 3)
Territory.create(id: 164, region_id: 19, name: 'Georgia(USA)', division_id: 3)
Territory.create(id: 163, region_id: 19, name: 'Florida(USA)', division_id: 3)
Territory.create(id: 16, region_id: 2, name: 'Japan', division_id: 1)
Territory.create(id: 173, region_id: 20, name: 'Lichtenstein', division_id: 3)
Territory.create(id: 170, region_id: 20, name: 'Hungary', division_id: 3)
Territory.create(id: 172, region_id: 20, name: 'Switzerland', division_id: 3)
Territory.create(id: 171, region_id: 20, name: 'Austria', division_id: 3)
Territory.create(id: 169, region_id: 20, name: 'Germany', division_id: 3)
Territory.create(id: 185, region_id: 21, name: 'Mayotte', division_id: 3)
Territory.create(id: 186, region_id: 21, name: 'Seycheles', division_id: 3)
Territory.create(id: 187, region_id: 21, name: 'Monaco', division_id: 3)
Territory.create(id: 182, region_id: 21, name: 'Gabon', division_id: 3)
Territory.create(id: 181, region_id: 21, name: 'Rep. Of Congo', division_id: 3)
Territory.create(id: 180, region_id: 21, name: 'Cen. Afric. Rep.', division_id: 3)
Territory.create(id: 183, region_id: 21, name: 'Reunion', division_id: 3)
Territory.create(id: 184, region_id: 21, name: 'Luxembourg', division_id: 3)
Territory.create(id: 179, region_id: 21, name: 'Burundi', division_id: 3)
Territory.create(id: 178, region_id: 21, name: 'Rwanda', division_id: 3)
Territory.create(id: 177, region_id: 21, name: 'Cameroon', division_id: 3)
Territory.create(id: 176, region_id: 21, name: 'Madagascar', division_id: 3)
Territory.create(id: 175, region_id: 21, name: 'Dem.Rep.of Congo', division_id: 3)
Territory.create(id: 174, region_id: 21, name: 'France', division_id: 3)
Territory.create(id: 192, region_id: 22, name: 'Guinnea Bissau', division_id: 3)
Territory.create(id: 194, region_id: 22, name: 'E. Timor', division_id: 3)
Territory.create(id: 195, region_id: 22, name: 'Cape Verde', division_id: 3)
Territory.create(id: 196, region_id: 22, name: 'Sao Tome and Principe', division_id: 3)
Territory.create(id: 197, region_id: 22, name: 'St. Lucia', division_id: 3)
Territory.create(id: 198, region_id: 22, name: 'St. Vincent', division_id: 3)
Territory.create(id: 199, region_id: 22, name: 'Grenada', division_id: 3)
Territory.create(id: 200, region_id: 22, name: 'St. Kitts', division_id: 3)
Territory.create(id: 190, region_id: 22, name: 'Angola', division_id: 3)
Territory.create(id: 193, region_id: 22, name: 'Trinadad & Tobago', division_id: 3)
Territory.create(id: 189, region_id: 22, name: 'Mozambique', division_id: 3)
Territory.create(id: 191, region_id: 22, name: 'Portugal', division_id: 3)
Territory.create(id: 188, region_id: 22, name: 'Brazil', division_id: 3)
Territory.create(id: 211, region_id: 23, name: 'Martinique', division_id: 3)
Territory.create(id: 213, region_id: 23, name: 'Vanuatu', division_id: 3)
Territory.create(id: 215, region_id: 23, name: 'French Guiana', division_id: 3)
Territory.create(id: 212, region_id: 23, name: 'Fr. Polynesian', division_id: 3)
Territory.create(id: 214, region_id: 23, name: 'New Caldonia', division_id: 3)
Territory.create(id: 210, region_id: 23, name: 'Guadaloupe', division_id: 3)
Territory.create(id: 209, region_id: 23, name: 'Togo', division_id: 3)
Territory.create(id: 207, region_id: 23, name: 'Guinea', division_id: 3)
Territory.create(id: 208, region_id: 23, name: 'Haiti', division_id: 3)
Territory.create(id: 205, region_id: 23, name: 'Mali', division_id: 3)
Territory.create(id: 206, region_id: 23, name: 'Senegal', division_id: 3)
Territory.create(id: 203, region_id: 23, name: 'Burkina Fasso', division_id: 3)
Territory.create(id: 204, region_id: 23, name: 'Niger', division_id: 3)
Territory.create(id: 202, region_id: 23, name: "Cote D' Ivoire", division_id: 3)
Territory.create(id: 201, region_id: 23, name: 'Canada', division_id: 3)
Territory.create(id: 230, region_id: 24, name: 'Cook Islands', division_id: 4)
Territory.create(id: 231, region_id: 24, name: 'Tahiti', division_id: 4)
Territory.create(id: 225, region_id: 24, name: 'Equatorial Guinea', division_id: 4)
Territory.create(id: 226, region_id: 24, name: 'Guyana', division_id: 4)
Territory.create(id: 227, region_id: 24, name: 'Samoa', division_id: 4)
Territory.create(id: 228, region_id: 24, name: 'Andorra', division_id: 4)
Territory.create(id: 229, region_id: 24, name: 'Bermuda', division_id: 4)
Territory.create(id: 220, region_id: 24, name: 'Bolivia', division_id: 4)
Territory.create(id: 221, region_id: 24, name: 'Domincan Rep.', division_id: 4)
Territory.create(id: 222, region_id: 24, name: 'Paraguay', division_id: 4)
Territory.create(id: 224, region_id: 24, name: 'Uraguay', division_id: 4)
Territory.create(id: 223, region_id: 24, name: 'Puerto Rico', division_id: 4)
Territory.create(id: 219, region_id: 24, name: 'Ecuador', division_id: 4)
Territory.create(id: 217, region_id: 24, name: 'Peru', division_id: 4)
Territory.create(id: 218, region_id: 24, name: 'Chile', division_id: 4)
Territory.create(id: 216, region_id: 24, name: 'Argentina', division_id: 4)
Territory.create(id: 235, region_id: 25, name: 'Belize', division_id: 4)
Territory.create(id: 244, region_id: 25, name: 'Barbados', division_id: 4)
Territory.create(id: 245, region_id: 25, name: 'Antigua & Barbuda', division_id: 4)
Territory.create(id: 246, region_id: 25, name: 'Dominica', division_id: 4)
Territory.create(id: 243, region_id: 25, name: 'Jamaica', division_id: 4)
Territory.create(id: 232, region_id: 25, name: 'Costa Rica', division_id: 4)
Territory.create(id: 242, region_id: 25, name: 'Panama', division_id: 4)
Territory.create(id: 241, region_id: 25, name: 'Nicaragua', division_id: 4)
Territory.create(id: 239, region_id: 25, name: 'Honduras', division_id: 4)
Territory.create(id: 240, region_id: 25, name: 'El Salvador', division_id: 4)
Territory.create(id: 233, region_id: 25, name: 'Benin', division_id: 4)
Territory.create(id: 234, region_id: 25, name: 'Cuba', division_id: 4)
Territory.create(id: 238, region_id: 25, name: 'Guatemala', division_id: 4)
Territory.create(id: 236, region_id: 25, name: 'Colombia', division_id: 4)
Territory.create(id: 237, region_id: 25, name: 'Venezuela', division_id: 4)
Territory.create(id: 252, region_id: 26, name: 'Vatican City', division_id: 3)
Territory.create(id: 250, region_id: 26, name: 'San Marino', division_id: 3)
Territory.create(id: 251, region_id: 26, name: 'New Jersey(USA)', division_id: 3)
Territory.create(id: 249, region_id: 26, name: 'New York(USA)', division_id: 3)
Territory.create(id: 248, region_id: 26, name: 'Spain', division_id: 3)
Territory.create(id: 247, region_id: 26, name: 'Italy', division_id: 3)
Territory.create(id: 258, region_id: 27, name: 'Washington DC(USA)', division_id: 4)
Territory.create(id: 257, region_id: 27, name: 'Finland', division_id: 4)
Territory.create(id: 256, region_id: 27, name: 'Maryland(USA)', division_id: 4)
Territory.create(id: 255, region_id: 27, name: 'Virginia(USA)', division_id: 4)
Territory.create(id: 253, region_id: 27, name: 'Sweden', division_id: 4)
Territory.create(id: 254, region_id: 27, name: 'Pennsylvania(USA)', division_id: 4)
Territory.create(id: 270, region_id: 28, name: 'Qatar', division_id: 0)
Territory.create(id: 272, region_id: 28, name: 'Bahrain', division_id: 3)
Territory.create(id: 269, region_id: 28, name: 'Oman', division_id: 3)
Territory.create(id: 264, region_id: 28, name: 'UAE', division_id: 3)
Territory.create(id: 400, region_id: 28, name: 'Kuwait', division_id: 3) #previous id 269
Territory.create(id: 271, region_id: 28, name: 'W. Virginia(USA)', division_id: 3)
Territory.create(id: 260, region_id: 28, name: 'Yemen', division_id: 3)
Territory.create(id: 268, region_id: 28, name: 'Kentucky(USA)', division_id: 3)
Territory.create(id: 259, region_id: 28, name: 'Norway', division_id: 3)
Territory.create(id: 267, region_id: 28, name: 'Wisconsin(USA)', division_id: 3)
Territory.create(id: 266, region_id: 28, name: 'Tennessee(USA)', division_id: 3)
Territory.create(id: 265, region_id: 28, name: 'Indiana(USA)', division_id: 3)
Territory.create(id: 263, region_id: 28, name: 'Michigan(USA)', division_id: 3)
Territory.create(id: 262, region_id: 28, name: 'Ohio(USA)', division_id: 3)
Territory.create(id: 261, region_id: 28, name: 'Illinois(USA)', division_id: 3)
Territory.create(id: 279, region_id: 29, name: 'N. Dakota(USA)', division_id: 4)
Territory.create(id: 278, region_id: 29, name: 'S. Dakota(USA)', division_id: 4)
Territory.create(id: 277, region_id: 29, name: 'Nebraska(USA)', division_id: 4)
Territory.create(id: 276, region_id: 29, name: 'Kansas(USA)', division_id: 4)
Territory.create(id: 275, region_id: 29, name: 'Oklahoma(USA)', division_id: 4)
Territory.create(id: 274, region_id: 29, name: 'Texas(USA)', division_id: 4)
Territory.create(id: 273, region_id: 29, name: 'Mexico', division_id: 4)
Territory.create(id: 18, region_id: 3, name: 'Guangxi', division_id: 1)
Territory.create(id: 23, region_id: 3, name: 'Macau', division_id: 1)
Territory.create(id: 21, region_id: 3, name: 'Hainan(China)', division_id: 1)
Territory.create(id: 19, region_id: 3, name: 'Jiangxi(China)', division_id: 1)
Territory.create(id: 17, region_id: 3, name: 'Hong Kong', division_id: 1)
Territory.create(id: 20, region_id: 3, name: 'Fujian(China)', division_id: 1)
Territory.create(id: 22, region_id: 3, name: 'Guangdong(China)', division_id: 1)
Territory.create(id: 290, region_id: 30, name: 'Suriname', division_id: 4)
Territory.create(id: 291, region_id: 30, name: 'Aruba', division_id: 4)
Territory.create(id: 292, region_id: 30, name: 'Netherland Antilles', division_id: 4)
Territory.create(id: 289, region_id: 30, name: 'Arkansas(USA)', division_id: 4)
Territory.create(id: 287, region_id: 30, name: 'Iowa(USA)', division_id: 4)
Territory.create(id: 288, region_id: 30, name: 'Mississippi(USA)', division_id: 4)
Territory.create(id: 285, region_id: 30, name: 'Alabama(USA)', division_id: 4)
Territory.create(id: 286, region_id: 30, name: 'Louisiana(USA)', division_id: 4)
Territory.create(id: 281, region_id: 30, name: 'Denmark', division_id: 4)
Territory.create(id: 283, region_id: 30, name: 'Missouri(USA)', division_id: 4)
Territory.create(id: 284, region_id: 30, name: 'Minnesota(USA)', division_id: 4)
Territory.create(id: 282, region_id: 30, name: 'Belgium', division_id: 4)
Territory.create(id: 280, region_id: 30, name: 'Netherlands', division_id: 4)
Territory.create(id: 303, region_id: 31, name: 'Jersey', division_id: 4)
Territory.create(id: 305, region_id: 31, name: 'Guernsey', division_id: 4)
Territory.create(id: 302, region_id: 31, name: 'Malta', division_id: 4)
Territory.create(id: 301, region_id: 31, name: 'Vermont(USA)', division_id: 4)
Territory.create(id: 304, region_id: 31, name: 'Isle of Man', division_id: 4)
Territory.create(id: 300, region_id: 31, name: 'Delaware(USA)', division_id: 4)
Territory.create(id: 299, region_id: 31, name: 'Rhode Island(USA)', division_id: 4)
Territory.create(id: 297, region_id: 31, name: 'Maine(USA)', division_id: 4)
Territory.create(id: 298, region_id: 31, name: 'New Hampshire(USA)', division_id: 4)
Territory.create(id: 296, region_id: 31, name: 'Connecticut(USA)', division_id: 4)
Territory.create(id: 295, region_id: 31, name: 'Ireland', division_id: 4)
Territory.create(id: 294, region_id: 31, name: 'Massachussetts(USA)', division_id: 4)
Territory.create(id: 293, region_id: 31, name: 'UK', division_id: 4)
Territory.create(id: 312, region_id: 32, name: 'Hawaii(USA)', division_id: 4)
Territory.create(id: 311, region_id: 32, name: 'New Mexico(USA)', division_id: 4)
Territory.create(id: 310, region_id: 32, name: 'Nevada(USA)', division_id: 4)
Territory.create(id: 309, region_id: 32, name: 'Utah(USA)', division_id: 4)
Territory.create(id: 308, region_id: 32, name: 'Colorado(USA)', division_id: 4)
Territory.create(id: 307, region_id: 32, name: 'Arizona(USA)', division_id: 4)
Territory.create(id: 306, region_id: 32, name: 'California(USA)', division_id: 4)
Territory.create(id: 320, region_id: 33, name: 'Wyoming(USA)', division_id: 4)
Territory.create(id: 319, region_id: 33, name: 'Alaska(USA)', division_id: 4)
Territory.create(id: 318, region_id: 33, name: 'Montana(USA)', division_id: 4)
Territory.create(id: 317, region_id: 33, name: 'Idaho(USA)', division_id: 4)
Territory.create(id: 314, region_id: 33, name: 'N.Korea', division_id: 4)
Territory.create(id: 316, region_id: 33, name: 'Oregon(USA)', division_id: 4)
Territory.create(id: 315, region_id: 33, name: 'Washington(USA)', division_id: 4)
Territory.create(id: 313, region_id: 33, name: 'S. Korea', division_id: 4)
Territory.create(id: 27, region_id: 4, name: 'Shanxi(China)', division_id: 1)
Territory.create(id: 31, region_id: 4, name: 'Tianjin', division_id: 1)
Territory.create(id: 30, region_id: 4, name: 'Beijing', division_id: 1)
Territory.create(id: 28, region_id: 4, name: 'Jilin(China)', division_id: 1)
Territory.create(id: 26, region_id: 4, name: 'Heilongjiang(China)', division_id: 1)
Territory.create(id: 25, region_id: 4, name: 'Liaoning(China)', division_id: 1)
Territory.create(id: 24, region_id: 4, name: 'Taiwan', division_id: 1)
Territory.create(id: 29, region_id: 4, name: 'Hebei(China)', division_id: 1)
Territory.create(id: 33, region_id: 5, name: 'An Hui(China)', division_id: 1)
Territory.create(id: 32, region_id: 5, name: 'Shanghai(China)', division_id: 1)
Territory.create(id: 38, region_id: 5, name: 'Philippines', division_id: 1)
Territory.create(id: 37, region_id: 5, name: 'Henan(China)', division_id: 1)
Territory.create(id: 34, region_id: 5, name: 'Zhejiang(China)', division_id: 1)
Territory.create(id: 36, region_id: 5, name: 'Jiangsu(China)', division_id: 1)
Territory.create(id: 35, region_id: 5, name: 'Shandong(China)', division_id: 1)
Territory.create(id: 44, region_id: 6, name: 'Inner Mongolia', division_id: 1)
Territory.create(id: 43, region_id: 6, name: 'Mongolia', division_id: 1)
Territory.create(id: 40, region_id: 6, name: 'Tibet', division_id: 1)
Territory.create(id: 41, region_id: 6, name: 'Qinghai(China)', division_id: 1)
Territory.create(id: 42, region_id: 6, name: 'Ningxia(China)', division_id: 1)
Territory.create(id: 45, region_id: 6, name: 'Gansu(China)', division_id: 1)
Territory.create(id: 39, region_id: 6, name: 'Xinjiang', division_id: 1)
Territory.create(id: 46, region_id: 7, name: 'Chongqing', division_id: 1)
Territory.create(id: 52, region_id: 7, name: 'Guizhou(China)', division_id: 1)
Territory.create(id: 47, region_id: 7, name: 'Yunnan(China)', division_id: 1)
Territory.create(id: 50, region_id: 7, name: 'Hunan(China)', division_id: 1)
Territory.create(id: 48, region_id: 7, name: 'Sichuan(China)', division_id: 1)
Territory.create(id: 49, region_id: 7, name: 'Shaanxi(China)', division_id: 1)
Territory.create(id: 51, region_id: 7, name: 'Hubei(China)', division_id: 1)
Territory.create(id: 57, region_id: 8, name: 'Laos', division_id: 1)
Territory.create(id: 60, region_id: 8, name: 'Brunei', division_id: 1)
Territory.create(id: 58, region_id: 8, name: 'Singapore', division_id: 1)
Territory.create(id: 55, region_id: 8, name: 'Sri Lanka', division_id: 1)
Territory.create(id: 54, region_id: 8, name: 'Myanmar/Burma', division_id: 1)
Territory.create(id: 53, region_id: 8, name: 'Thailand`', division_id: 1)
Territory.create(id: 56, region_id: 8, name: 'Malaysia', division_id: 1)
Territory.create(id: 59, region_id: 8, name: 'Indonesia', division_id: 1)
Territory.create(id: 71, region_id: 9, name: 'Estonia', division_id: 2)
Territory.create(id: 67, region_id: 9, name: 'Kyrgyzstan', division_id: 2)
Territory.create(id: 68, region_id: 9, name: 'Turkmenistan', division_id: 2)
Territory.create(id: 66, region_id: 9, name: 'Tajikstan', division_id: 2)
Territory.create(id: 70, region_id: 9, name: 'Latvia', division_id: 2)
Territory.create(id: 65, region_id: 9, name: 'Belarus', division_id: 2)
Territory.create(id: 64, region_id: 9, name: 'Kazakstan', division_id: 2)
Territory.create(id: 69, region_id: 9, name: 'Lithuania', division_id: 2)
Territory.create(id: 63, region_id: 9, name: 'Uzbekistan', division_id: 2)
Territory.create(id: 61, region_id: 9, name: 'Ukraine', division_id: 2)
Territory.create(id: 62, region_id: 9, name: 'Russia', division_id: 2)


Region.create(id: 1, name: 'Region 1')
Region.create(id: 10, name: 'Region 10')
Region.create(id: 11, name: 'Region 11')
Region.create(id: 12, name: 'Region 12')
Region.create(id: 13, name: 'Region 13')
Region.create(id: 14, name: 'Region 14')
Region.create(id: 16, name: 'Region 16')
Region.create(id: 15, name: 'Region 15')
Region.create(id: 17, name: 'Region 17')
Region.create(id: 18, name: 'Region 18')
Region.create(id: 19, name: 'Region 19')
Region.create(id: 20, name: 'Region 20')
Region.create(id: 21, name: 'Region 21')
Region.create(id: 22, name: 'Region 22')
Region.create(id: 23, name: 'Region 23')
Region.create(id: 24, name: 'Region 24')
Region.create(id: 25, name: 'Region 25')
Region.create(id: 26, name: 'Region 26')
Region.create(id: 27, name: 'Region 27')
Region.create(id: 28, name: 'Region 28')
Region.create(id: 29, name: 'Region 29')
Region.create(id: 3, name: 'Region 3')
Region.create(id: 30, name: 'Region 30')
Region.create(id: 31, name: 'Region 31')
Region.create(id: 32, name: 'Region 32')
Region.create(id: 33, name: 'Region 33')
Region.create(id: 4, name: 'Region 4')
Region.create(id: 5, name: 'Region 5')
Region.create(id: 6, name: 'Region 6')
Region.create(id: 7, name: 'Region 7')
Region.create(id: 8, name: 'Region 8')
Region.create(id: 9, name: 'Region 9')
Region.create(id: 2, name: 'Region 2')


Division.create(id: 1, name: 'Eastern Division')
Division.create(id: 2, name: 'East Central')
Division.create(id: 3, name: 'West Central')
Division.create(id: 4, name: 'Western Divisions')
Division.create(id: 5, name: 'All Divisions')


Role.create(name: 'Regional Representative')
Role.create(name: 'Divisional Director')
Role.create(name: 'Data Acquisition Personnel')
Role.create(name: 'Senior Director')


User.create(user_main_id: '4432001', password: 'Rosa123', password_confirmation: 'Rosa123', first_name: 'Rosa', middle_name: 'Linda', last_name: 'Onofre', division_id: 4, region_id: 32, title: 'Western Division Director Of Operations', email: 'rosa@louisp.info', role_id: 2, region_user_number: 1, job_reference: 'Western Division Director Of Operations' )
User.create(user_main_id: '2213001', password: 'Kavleen', password_confirmation: 'Kavleen', first_name: 'Kavleen ', middle_name: '', last_name: 'Gujral', division_id: 2, region_id: 13, title: 'East-Central Division Director Of Opertaions', email: 'kavleen@louisp.info', role_id: 2, region_user_number: 1, job_reference: 'East-Central Division Director Of Opertaions' )
User.create(user_main_id: '2011001', password: 'Alex123', password_confirmation: 'Alex123', first_name: 'Alex', middle_name: '', last_name: 'Surong', division_id: 2, region_id: 11, title: 'Regional Representative Region 11', email: 'alex@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 11' )
User.create(user_main_id: '3022001', password: 'Yan123', password_confirmation: 'Yan123', first_name: 'Yan ', middle_name: '', last_name: 'Whately', division_id: 3, region_id: 23, title: 'Regional Representative Region 21', email: 'yan@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 21' )
User.create(user_main_id: '2015001', password: 'Can123', password_confirmation: 'Can123', first_name: 'Mehmet Can', middle_name: '', last_name: 'Sezgin', division_id: 2, region_id: 15, title: 'Regional Representative Region 14', email: 'mcsezgin@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 14' )
User.create(user_main_id: '2016001', password: 'Samer123', password_confirmation: 'Samer123', first_name: 'Samer', middle_name: 'Fakhreldin Ahmed Mohsen', last_name: 'Abdelhalim', division_id: 2, region_id: 16, title: 'Regional Representative Region 15', email: 'samer@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 15' )
User.create(user_main_id: '3321001', password: 'Clelia123', password_confirmation: 'Clelia123', first_name: 'Clélia', middle_name: '', last_name: 'Hardy', division_id: 3, region_id: 21, title: 'West-Central Division Director of Operations', email: 'clelia@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'West-Central Division Director of Operations' )
User.create(user_main_id: '3026001', password: 'Silvia123', password_confirmation: 'Silvia123', first_name: 'Silvia', middle_name: '', last_name: 'Martinez', division_id: 3, region_id: 26, title: 'Regional Representative Region 25', email: 'silvia@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 25' )
User.create(user_main_id: '1004001', password: 'Sara123', password_confirmation: 'Sara123', first_name: 'Sara', middle_name: '', last_name: 'Ceesay', division_id: 1, region_id: 4, title: 'Regional Representative Region 4', email: 'sara@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 4' )
User.create(user_main_id: '1101001', password: 'Mitch123', password_confirmation: 'Mitch123', first_name: 'Mitch ', middle_name: '', last_name: 'St. Pierre', division_id: 1, region_id: 1, title: 'Eastern Division Director of Operations', email: 'mitch@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Eastern Division Director of Operations' )
User.create(user_main_id: '1003001', password: 'Carrie123', password_confirmation: 'Carrie123', first_name: 'Carrie', middle_name: 'Anne', last_name: 'Yu', division_id: 1, region_id: 3, title: 'Regional Representative Region 3', email: 'carrie@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 3' )
User.create(user_main_id: '2009001', password: 'Andrey123', password_confirmation: 'Andrey123', first_name: 'Andrey', middle_name: 'Goncharenko', last_name: 'Konstantinovich', division_id: 2, region_id: 9, title: 'Regional Representative Region 8', email: 'andrey@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 8' )
User.create(user_main_id: '4025001', password: 'Jason123', password_confirmation: 'Jason123', first_name: 'Jason', middle_name: 'Siliani', last_name: 'Zuñiga', division_id: 4, region_id: 25, title: 'Regional Representative Region 24', email: 'jason@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 24' )
User.create(user_main_id: '1007001', password: 'Jerry123', password_confirmation: 'Jerry123', first_name: ' Liang "Jerry"', middle_name: '', last_name: 'Sun', division_id: 1, region_id: 7, title: 'Regional Representative, Region 6', email: 'jerry@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative, Region 6' )
User.create(user_main_id: '3028001', password: 'Adam123', password_confirmation: 'Adam123', first_name: 'Adam', middle_name: '', last_name: 'Shocair', division_id: 3, region_id: 28, title: 'Regional Representative Region 27', email: 'adam@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 27' )
User.create(user_main_id: '3030001', password: 'Saskia123', password_confirmation: 'Saskia123', first_name: 'Saskia', middle_name: '', last_name: 'Cervello', division_id: 3, region_id: 30, title: 'Regional Representative Region 29', email: 'saskia@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 29' )
User.create(user_main_id: '4029001', password: 'Victoria123', password_confirmation: 'Victoria123', first_name: 'Viktoryia', middle_name: '', last_name: 'Abramtsava', division_id: 4, region_id: 29, title: 'Regional Representative Region 28-29', email: 'Victoria@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 28-29' )
User.create(user_main_id: '3019001', password: 'Elisha123', password_confirmation: 'Elisha123', first_name: 'Elisha', middle_name: '', last_name: 'Jacobsen', division_id: 3, region_id: 19, title: 'Regional Representative Region 19', email: 'Elisha@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 19' )
User.create(user_main_id: '1008001', password: 'Erik1234', password_confirmation: 'Erik1234', first_name: 'Erik', middle_name: '', last_name: 'Rempen', division_id: 1, region_id: 8, title: 'Regional Representative Region 8', email: 'Erik@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 8' )
User.create(user_main_id: '4024001', password: 'Maria123', password_confirmation: 'Maria123', first_name: 'Maria Jose', middle_name: '', last_name: 'Semino', division_id: 4, region_id: 24, title: 'Regional Representative Region 25', email: 'Maria', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 25' )
User.create(user_main_id: '3020001', password: 'Andy1234', password_confirmation: 'Andy1234', first_name: 'Andy ', middle_name: '', last_name: 'Watts', division_id: 3, region_id: 20, title: 'Regional Representative Region 20', email: 'Andy@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 20' )
User.create(user_main_id: '2010001', password: 'Jason123', password_confirmation: 'Jason123', first_name: 'Jason', middle_name: ' Ward', last_name: 'Kharkonger', division_id: 2, region_id: 10, title: 'Regional Representative Region 10', email: 'jasonward@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 10' )

User.create(user_main_id: '1005001', password: 'Juan1234', password_confirmation: 'Juan1234', first_name: 'Juan', middle_name: '', last_name: 'Ibagon', division_id: 1, region_id: 5, title: 'Regional Representative Region 5', email: 'juan@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 5' )
User.create(user_main_id: '5001001', password: 'Brian1234', password_confirmation: 'Brian1234', first_name: 'Brian', middle_name: '', last_name: 'Martin', division_id: 5, region_id: 1, title: 'Development Director', email: 'brian@louisp.info', role_id: 4, region_user_number: 1, job_reference: 'Development Director' )
User.create(user_main_id: '5002001', password: 'Brad1234', password_confirmation: 'Brad1234', first_name: 'Brad', middle_name: '', last_name: 'Gardner', division_id: 5, region_id: 2, title: '', email: 'Brad@louisp.info', role_id: 4, region_user_number: 1, job_reference: '' )
User.create(user_main_id: '2014001', password: 'Nouran123', password_confirmation: 'Nouran123', first_name: 'Nouran', middle_name: '', last_name: 'Sleat', division_id: 2, region_id: 14, title: 'Regional Representative Region 14', email: 'Nouran@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 14' )
User.create(user_main_id: '3017001', password: 'Valencia123', password_confirmation: 'Valencia123', first_name: 'Valencia', middle_name: '', last_name: 'Visagie', division_id: 3, region_id: 17, title: 'Regional Representative Region 17', email: 'Valencia@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 17' )
User.create(user_main_id: '4023001', password: 'Scott123', password_confirmation: 'Scott123', first_name: 'Scott', middle_name: '', last_name: 'Sanderson', division_id: 4, region_id: 23, title: 'Regional Representative Region 23', email: 'Scott@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 23' )

User.create(user_main_id: '3031001', password: 'Cristian123', password_confirmation: 'Cristian123', first_name: 'Cristian', middle_name: '', last_name: 'Soriano', division_id: 3, region_id: 31, title: 'Regional Representative Region 31', email: 'Cristian@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 31' )

User.create(user_main_id: '3017001', password: 'Valencia123', password_confirmation: 'Valencia123', first_name: 'Valencia', middle_name: '', last_name: 'Visagie', division_id: 3, region_id: 17, title: 'Regional Representative Region 17', email: 'Valencia@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 17' )


User.create(user_main_id: '4024002', password: 'Paula123', password_confirmation: 'Paula123', first_name: 'Paula', middle_name: '', last_name: 'Paniagua', division_id: 4, region_id: 24, title: 'Regional Representative Region 24', email: 'Paula@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 17' )
User.create(user_main_id: '1006001', password: 'Ndey12345', password_confirmation: 'Ndey12345', first_name: 'Ndey', middle_name: '', last_name: 'Ndiaye', division_id: 1, region_id: 6, title: 'Regional Representative Region 6', email: 'ndey@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 17' )
User.create(user_main_id: '2018001', password: 'Katerina123', password_confirmation: 'Katerina123', first_name: 'Katerina', middle_name: '', last_name: 'Ilijovska', division_id: 2, region_id: 18, title: 'Regional Representative Region 18', email: 'Katerina@louisp.info', role_id: 1, region_user_number: 1, job_reference: 'Regional Representative Region 17' )
